# Generated by Django 5.2.12 on 2026-03-12 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cours",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("temps_apprentissage", models.IntegerField(default=0)),
                ("is_published", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nom", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("mot_de_passe", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("etudiant", "Etudiant"),
                            ("enseignant", "Enseignant"),
                            ("admin", "Admin"),
                        ],
                        default="etudiant",
                        max_length=20,
                    ),
                ),
                ("token", models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Enseignant",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="API.utilisateur",
                    ),
                ),
                ("specialite", models.CharField(max_length=255)),
            ],
            bases=("API.utilisateur",),
        ),
        migrations.CreateModel(
            name="Etudiant",
            fields=[
                (
                    "utilisateur_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="API.utilisateur",
                    ),
                ),
                ("progression", models.FloatField(default=0.0)),
                ("score_moyen", models.FloatField(default=0.0)),
            ],
            bases=("API.utilisateur",),
        ),
        migrations.AddField(
            model_name="cours",
            name="enseignant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cours",
                to="API.enseignant",
            ),
        ),
        migrations.CreateModel(
            name="Inscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("note_moyenne", models.FloatField(default=0.0)),
                ("evaluation", models.IntegerField(blank=True, null=True)),
                ("termine", models.BooleanField(default=False)),
                ("progression_percent", models.FloatField(default=0.0)),
                ("date_inscription", models.DateTimeField(auto_now_add=True)),
                ("date_mise_a_jour", models.DateTimeField(auto_now=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="API.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inscriptions",
                        to="API.etudiant",
                    ),
                ),
            ],
            options={
                "unique_together": {("etudiant", "cours")},
            },
        ),
        migrations.AddField(
            model_name="etudiant",
            name="cours",
            field=models.ManyToManyField(
                related_name="etudiants_liste",
                through="API.Inscription",
                to="API.cours",
            ),
        ),
        migrations.AddField(
            model_name="cours",
            name="etudiants",
            field=models.ManyToManyField(
                related_name="cours_liste",
                through="API.Inscription",
                to="API.etudiant",
            ),
        ),
        migrations.CreateModel(
            name="Lecon",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=255)),
                ("contenu", models.TextField()),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("duree_estimee_minutes", models.PositiveIntegerField(default=0)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lecons",
                        to="API.cours",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titre", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "niveau",
                    models.CharField(
                        choices=[
                            ("debutant", "Débutant"),
                            ("intermediaire", "Intermédiaire"),
                            ("avance", "Avancé"),
                        ],
                        default="debutant",
                        max_length=20,
                    ),
                ),
                ("temps_limite_minutes", models.PositiveIntegerField(default=0)),
                ("tentatives_autorisees", models.PositiveIntegerField(default=1)),
                ("score_reussite", models.FloatField(default=10.0)),
                ("score_max", models.FloatField(default=20.0)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("brouillon", "Brouillon"),
                            ("publie", "Publié"),
                            ("archive", "Archivé"),
                        ],
                        default="brouillon",
                        max_length=20,
                    ),
                ),
                ("melanger_questions", models.BooleanField(default=False)),
                ("afficher_feedback", models.BooleanField(default=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                ("date_publication", models.DateTimeField(blank=True, null=True)),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="API.cours",
                    ),
                ),
                (
                    "enseignant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="API.enseignant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("enonce", models.TextField()),
                (
                    "type_question",
                    models.CharField(
                        choices=[
                            ("choix_unique", "Choix unique"),
                            ("choix_multiple", "Choix multiple"),
                            ("vrai_faux", "Vrai/Faux"),
                            ("reponse_courte", "Réponse courte"),
                        ],
                        default="choix_unique",
                        max_length=30,
                    ),
                ),
                ("points", models.FloatField(default=1.0)),
                ("ordre", models.PositiveIntegerField(default=1)),
                ("explication", models.TextField(blank=True, null=True)),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="API.quiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChoixQuestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("texte", models.CharField(max_length=255)),
                ("est_correct", models.BooleanField(default=False)),
                ("ordre", models.PositiveIntegerField(default=1)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choix",
                        to="API.question",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TentativeQuiz",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("numero_tentative", models.PositiveIntegerField(default=1)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_cours", "En cours"),
                            ("soumis", "Soumis"),
                            ("corrige", "Corrigé"),
                            ("abandonne", "Abandonné"),
                        ],
                        default="en_cours",
                        max_length=20,
                    ),
                ),
                ("score", models.FloatField(default=0.0)),
                ("score_max", models.FloatField(default=20.0)),
                ("pourcentage", models.FloatField(default=0.0)),
                ("reussi", models.BooleanField(default=False)),
                ("date_debut", models.DateTimeField(auto_now_add=True)),
                ("date_soumission", models.DateTimeField(blank=True, null=True)),
                ("temps_passe_secondes", models.PositiveIntegerField(default=0)),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives_quiz",
                        to="API.etudiant",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tentatives",
                        to="API.quiz",
                    ),
                ),
            ],
            options={
                "unique_together": {("quiz", "etudiant", "numero_tentative")},
            },
        ),
        migrations.CreateModel(
            name="ReponseTentative",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("reponse_texte", models.TextField(blank=True, null=True)),
                ("est_correcte", models.BooleanField(blank=True, null=True)),
                ("points_obtenus", models.FloatField(default=0.0)),
                (
                    "choix_selectionne",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reponses_selectionnees",
                        to="API.choixquestion",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses_tentatives",
                        to="API.question",
                    ),
                ),
                (
                    "tentative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reponses",
                        to="API.tentativequiz",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SessionApprentissage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("duree_minutes", models.PositiveIntegerField(default=0)),
                ("date_session", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_apprentissage",
                        to="API.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions_apprentissage",
                        to="API.etudiant",
                    ),
                ),
                (
                    "lecon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sessions_apprentissage",
                        to="API.lecon",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recommandation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("score_recommendation", models.FloatField()),
                (
                    "cours",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API.cours",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="API.utilisateur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HistoriqueActivite",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "type_activite",
                    models.CharField(
                        choices=[
                            ("quiz_reussi", "Quiz réussi"),
                            ("quiz_echoue", "Quiz échoué"),
                            ("cours_demarre", "Cours démarré"),
                            ("cours_termine", "Cours terminé"),
                            ("lecon_consultee", "Leçon consultée"),
                            ("session_etude", "Session d’étude"),
                        ],
                        max_length=30,
                    ),
                ),
                ("titre", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255, null=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                (
                    "cours",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_activites",
                        to="API.cours",
                    ),
                ),
                (
                    "etudiant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_activites",
                        to="API.etudiant",
                    ),
                ),
                (
                    "lecon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_activites",
                        to="API.lecon",
                    ),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="historique_activites",
                        to="API.quiz",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_creation"],
            },
        ),
    ]