# Generated by Django 5.2.12 on 2026-04-29 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommandation',
            unique_together={('utilisateur', 'cours')},
        ),
    ]
