# Generated by Django 5.2.12 on 2026-04-03 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cours',
            name='is_published',
        ),
    ]
