# Generated by Django 5.2.12 on 2026-03-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='role',
            field=models.CharField(choices=[('debutant', 'Debutant'), ('intermediaire', 'Intermediaire'), ('avance', 'Avance')], default='debutant', max_length=20),
        ),
    ]
