# Generated by Django 4.2.29 on 2026-03-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
