# Generated by Django 4.2.29 on 2026-03-19 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueActivite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_activite', models.CharField(choices=[('quiz_reussi', 'Quiz réussi'), ('quiz_echoue', 'Quiz échoué'), ('cours_demarre', 'Cours démarré'), ('cours_termine', 'Cours terminé'), ('lecon_consultee', 'Leçon consultée'), ('session_etude', 'Session d’étude')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_activites', to='API.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_activites', to='API.etudiant')),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_activites', to='API.lecon')),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historique_activites', to='API.quiz')),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
