# Generated by Django 5.2.12 on 2026-03-16 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_cours_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='role',
            new_name='niveau',
        ),
    ]
