# Generated by Django 4.2.29 on 2026-03-12 08:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_utilisateur_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoixQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=255)),
                ('est_correct', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ReponseTentative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_texte', models.TextField(blank=True, null=True)),
                ('est_correcte', models.BooleanField(blank=True, null=True)),
                ('points_obtenus', models.FloatField(default=0.0)),
                ('choix_selectionne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reponses_selectionnees', to='API.choixquestion')),
            ],
        ),
        migrations.CreateModel(
            name='TentativeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tentative', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('soumis', 'Soumis'), ('corrige', 'Corrigé'), ('abandonne', 'Abandonné')], default='en_cours', max_length=20)),
                ('score', models.FloatField(default=0.0)),
                ('score_max', models.FloatField(default=0.0)),
                ('pourcentage', models.FloatField(default=0.0)),
                ('reussi', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('temps_passe_secondes', models.PositiveIntegerField(default=0)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives_quiz', to='API.etudiant')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='reponse_correcte',
        ),
        migrations.AddField(
            model_name='question',
            name='explication',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='question',
            name='type_question',
            field=models.CharField(choices=[('choix_unique', 'Choix unique'), ('choix_multiple', 'Choix multiple'), ('vrai_faux', 'Vrai/Faux'), ('reponse_courte', 'Réponse courte')], default='choix_unique', max_length=30),
        ),
        migrations.AddField(
            model_name='quiz',
            name='afficher_feedback',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_publication',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='enseignant',
            field=models.ForeignKey(default=37, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='API.enseignant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='melanger_questions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_reussite',
            field=models.FloatField(default=10.0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='statut',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
        migrations.AddField(
            model_name='quiz',
            name='temps_limite_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quiz',
            name='tentatives_autorisees',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cours', to='API.enseignant'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='API.cours'),
        ),
        migrations.AlterField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='API.quiz'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='API.cours'),
        ),
        migrations.DeleteModel(
            name='Resultat',
        ),
        migrations.AddField(
            model_name='tentativequiz',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tentatives', to='API.quiz'),
        ),
        migrations.AddField(
            model_name='reponsetentative',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses_tentatives', to='API.question'),
        ),
        migrations.AddField(
            model_name='reponsetentative',
            name='tentative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='API.tentativequiz'),
        ),
        migrations.AddField(
            model_name='choixquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='API.question'),
        ),
        migrations.AlterUniqueTogether(
            name='tentativequiz',
            unique_together={('quiz', 'etudiant', 'numero_tentative')},
        ),
    ]
