# Generated by Django 5.2.12 on 2026-04-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_utilisateur_date_registered_utilisateur_last_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
    ]
