# Generated by Django 4.2.29 on 2026-03-12 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_choixquestion_reponsetentative_tentativequiz_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "API_cours"
                ADD COLUMN IF NOT EXISTS temps_apprentissage integer NOT NULL DEFAULT 0;
            """,
            reverse_sql="""
                ALTER TABLE "API_cours"
                DROP COLUMN IF EXISTS temps_apprentissage;
            """
        ),
    ]