# Generated by Django 5.2.12 on 2026-04-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_utilisateur_force_password_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='temp_password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
