# Generated by Django 5.2.12 on 2026-04-08 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_utilisateur_temp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='temp_password_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
