# Generated by Django 4.2.29 on 2026-03-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_sync_cours_temps_apprentissage'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='niveau',
            field=models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20),
        ),
    ]
