# Generated by Django 5.2.12 on 2026-03-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_alter_cours_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=20),
        ),
    ]
