# Generated by Django 5.2.12 on 2026-03-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_cours_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='ordre',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenu',
            field=models.FileField(blank=True, null=True, upload_to='lecons/'),
        ),
    ]
