# Generated by Django 4.2.29 on 2026-03-18 10:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0005_quiz_niveau'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cours',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='date_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='inscription',
            name='progression_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lecon',
            name='duree_estimee_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lecon',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='score_max',
            field=models.FloatField(default=20.0),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='cours',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='API.cours'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='API.etudiant'),
        ),
        migrations.AlterField(
            model_name='tentativequiz',
            name='score_max',
            field=models.FloatField(default=20.0),
        ),
        migrations.CreateModel(
            name='SessionApprentissage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('date_session', models.DateTimeField(auto_now_add=True)),
                ('cours', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_apprentissage', to='API.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_apprentissage', to='API.etudiant')),
                ('lecon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_apprentissage', to='API.lecon')),
            ],
        ),
    ]
