# Generated by Django 5.2.12 on 2026-04-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_passwordresetrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetrequest',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
