# Generated by Django 5.2.12 on 2026-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_lecon_ordre_alter_lecon_contenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='banniere',
            field=models.ImageField(blank=True, null=True, upload_to='bannieres/'),
        ),
    ]
