# Generated by Django 5.2.12 on 2026-03-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_cours_banniere'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='status',
            field=models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié'), ('archive', 'Archivé')], default='brouillon', max_length=20),
        ),
    ]
