# Generated by Django 4.2.29 on 2026-03-23 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_historiqueactivite'),
        ('API', '0007_cours_banniere'),
    ]

    operations = [
    ]
