# Generated by Django 4.2.29 on 2026-03-24 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_merge_0002_historiqueactivite_0007_cours_banniere'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='favoris',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lecon',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='lecons/'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='ordre',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
