# Generated by Django 5.2.12 on 2026-03-26 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_cours_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='category',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
