# Generated by Django 4.2.29 on 2026-03-27 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_cours_category'),
        ('API', '0009_inscription_favoris_lecon_fichier_and_more'),
    ]

    operations = [
    ]
