# Generated by Django 5.2.12 on 2026-03-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_cours_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_registered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='last_online',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
