# Generated by Django 4.2.29 on 2026-03-30 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_merge_20260327_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionLecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_vues_max', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('progression_percent', models.FloatField(default=0.0)),
                ('terminee', models.BooleanField(default=False)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to='API.cours')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to='API.etudiant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions_lecons', to='API.lecon')),
            ],
            options={
                'unique_together': {('etudiant', 'cours', 'lecon')},
            },
        ),
    ]
